### ISSUE TITLE
Doubt

### ISSUE THREAD

**Issue by pakchoi-php** [davidnvq/me_recognition#10]
![EO3PMQ6RVC72MKPP1PU@OVJ](https://user-images.githubusercontent.com/51792701/155723443-d32b5244-b36a-41b9-9f96-7437ffab34e0.png)

![NR@XX)0DF`S3(75~YGKGIDP](https://user-images.githubusercontent.com/51792701/155723470-bb621a6e-5dec-4b89-95f3-114b74e4a414.png)
I'm sorry to bother you, but I don't understand how this piece of data is sampled. Why is there value, why is the neg value of 4.

**Comment by pakchoi-php** [comment]
why num_sur=4?

**Comment by quangvnai** [comment]
Thanks for your interest in the code.
* `num_sur` is the ratio number of samples with class `surprise` emotion you want to upsample.
* `num_pos` is the ratio number of samples with class `position` emotion you want to upsample.
* `num_neg` is the ratio number of samples with class `negative` emotion  you want to upsample.

`value` is just a rounded value (added some tiny randomness) of `num_sur`, `num_pos`, and `num_neg`.
For example, if `num_pos` = 5.12, then `value` is likely = 5. If `num_pos` = `5.89` then value is likely = 6.

In fact, I decided to upsample for the class `surprise` 4 times based on the statistics of datasets. You can change it to any number, indeed.

**Comment by pakchoi-php** [comment]
Thank you very much for your reply。
