### ISSUE TITLE
UF1和UAR值的问题

### ISSUE THREAD

**Issue by pakchoi-php** [davidnvq/me_recognition#11]
![image](https://user-images.githubusercontent.com/51792701/160099437-c6df4dc7-9dd7-41a3-b4ae-f61ab4e4defa.png)
我在得到每一次的uf1,uf2是不是要存储起来 除以24 然后我得到的结果和论文结果相差甚远，还有论文中提到了k folds of LOSO  代码中的Kfolds定义的UF1并未调用，我怎样才能得到论文结果呢

**Comment by pakchoi-php** [comment]
我裁剪后得到了提高

**Comment by quangvnai** [comment]
Oops, Sorry I've just checked the Github. It seems like you already got a good performance (translated by Google as I'm not a Chinese).
For reproducibility, there was another user who retrained and put the checkpoint [here](https://github.com/davidnvq/me_recognition/tree/master/trained).
