### ISSUE TITLE
Final scores

### ISSUE THREAD

**Issue by MendesEric** [davidnvq/me_recognition#12]
I was reading your paper and code but I didn't understand how do you get on that scores showed on paper. I know you use LOSO protocol where you obtain UAR and UF1 for each subject test while training with others. So, the final UAR and UF1 are the mean of every single one obtained or you calculate differently?
![imagem_2022-06-08_171318713](https://user-images.githubusercontent.com/78175152/172708359-774860ec-a7c4-4a16-84c0-bea1b415b8b9.png)

**Comment by quangvnai** [comment]
The answer for your question can be found here https://github.com/davidnvq/me_recognition/issues/13, in which I replied a similar question.
