### ISSUE TITLE
protocol

### ISSUE THREAD

**Issue by pakchoi-php** [davidnvq/me_recognition#13]
Hello, I would like to ask whether the UF1 and UAR of CASMEII are obtained under the model with 68 subjects training, or only this one case of CASMEII training, I am a little confused about this protocol？Looking forward to your reply, thank you very much.

**Comment by quangvnai** [comment]
I am sorry for the very late reply (just from the holidays). 
The evaluate protocol is LOSO **(leave-one-subject-out)** over all 68 subjects.
Specificially, the model is trained in 67 subjects, and it is evaluated on subject 1 -> which yields best UF1 and UAR, say **scores 1**.
We repeated this procedure until the evaluation on subject 68, which yields best UF1 and UAR - corresponding to **score 68**.

The final UF1 and UAR are the means of all above UF1 and UAR, respectively.
Hope it clears your question.

**Comment by pakchoi-php** [comment]
Thank you very much for your reply.





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "davidnvq/me_recognition"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月28日(星期二) 晚上6:12
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [davidnvq/me_recognition] protocol (Issue #13)





 
I am sorry for the very late reply (just from the holidays).
 The evaluate protocol is LOSO (Leave-One-Out Cross-Validation) over all 68 subjects.
 Specificially, the model is trained in 67 subjects, and it is evaluated on subject 1 -&gt; which yields best UF1 and UAR, say scores 1.
 We repeated this procedure until the evaluation on subject 68, which yields best UF1 and UAR - corresponding to score 68.
 
The final UF1 and UAR are the means of all above UF1 and UAR, respectively.
 Hope it clears your question.

**Comment by quangvnai** [comment]
You're welcome and again sorry for the delay.
