### ISSUE TITLE
file not exits

### ISSUE THREAD

**Issue by YUZHIWANG-bug** [davidnvq/me_recognition#15]
Some missing and invalid clips
There are 7 clip files which are missing or invalid.
The below clips don't exist in the downloaded datasets

Could you tell me how to solve this file？

**Comment by quangvnai** [comment]
I'm sorry for late reply. 
Indeed, the missing and invalid clips are excluded during training/validation.

**Comment by Kabir1L** [comment]
I tried to redeploy and exclude the given files and kept them in a backup folder, and I am currently getting this error
<img width="996" alt="Screenshot 2024-06-25 at 7 53 21 PM" src="https://github.com/davidnvq/me_recognition/assets/152347059/2d5baa60-e222-40c1-97b8-da7af4ea014b">
any ideas what fix can be done as an initial interpretation was made that it was hardcoded
