### ISSUE TITLE
NameError: global name 'fer_weight_path' is not defined

### ISSUE THREAD

**Issue by matak07** [davidnvq/me_recognition#2]
Hi @quanguet ,

As mentioned in the README file, I tried running traon_me_loso.py file, but I keep getting the following error. I could find the variable that is giving the error but it is nowhere initialized in the code. Can you suggest where is it to be initialized or what value should be assigned to the variable.

/usr/bin/python3.5 /../../../../codes/me_recognition-master/train_me_loso.py
Traceback (most recent call last):
  File "/../../../../codes/me_recognition-master/train_me_loso.py", line 185, in <module>
    scores = train_eval(subject_out_idx=i)
  File "/../../../../codes/me_recognition-master/train_me_loso.py", line 154, in train_eval
    model.load_state_dict(torch.load(fer_weight_path)['model'])
NameError: name 'fer_weight_path' is not defined

Process finished with exit code 1

**Comment by davidnvq** [comment]
Hi @matak07, please forgive me since I couldn't get the notification for your issue on Github. As I see your issue was several months ago. I may close the problem but feel free to re-open it if necessary. Many thanks.
