### ISSUE TITLE
couldn't find 'fer_weight_path'

### ISSUE THREAD

**Issue by CodeYu529** [davidnvq/me_recognition#4]
hello,this is a  nice code! It's helpful for me.But i can't find the fer_weight_path.

**Comment by davidnvq** [comment]
I believe that you are talking about line 154 in [this file](https://github.com/davidnvq/me_recognition/blob/master/train_me_loso.py). I think you can uncomment this line as its purpose is to load the saved checkpoint.

**Comment by CodeYu529** [comment]
Thanks for your reply！Now, i only have the Casme2 dataset, how could i modify the code to train the Casme2 and get the result？

**Comment by CodeYu529** [comment]
Thanks for your reply！Now, i only have the Casme2 dataset, how could i modify the code to train the Casme2 and get the result？

**Comment by davidnvq** [comment]
Sorry for delayed reply. If so, to use the https://github.com/davidnvq/me_recognition/blob/master/train_me_loso.py, you just need to modify the dataset in the 2 files: `'datasets/data_apex.csv'` and `'datasets/data_four_frames.csv'`.  Simply, keep only the rows corresponding to Casme2 and delete all the other rows. Hope this help!
