### ISSUE TITLE
Why loop 68 times

### ISSUE THREAD

**Issue by Ritian-Li** [davidnvq/me_recognition#6]
https://github.com/davidnvq/me_recognition/blob/038b6333d4ab56366f0d1f1f10ec9e6e8ac147eb/train_me_loso.py#L184

**Comment by davidnvq** [comment]
@Ritian-Li Thanks for asking. There are 68 subjects in the combined datasets. `train_me_loso.py` indicates the Leave-One-Subject-Out pipeline. Thus, we validate a model on 1 subject in which this model has been trained on the other 67 subjects; and we repeat this train-and-validate procedure on each subject. That's why we have the number `68`.

**Comment by Ritian-Li** [comment]
> @Ritian-Li Thanks for asking. There are 68 subjects in the combined datasets. `train_me_loso.py` indicates the Leave-One-Subject-Out pipeline. Thus, we validate a model on 1 subject in which this model has been trained on the other 67 subjects; and we repeat this train-and-validate procedure on each subject. That's why we have the number `68`.

Thank you for your reply! I read your paper again, it's a wonderful work. In paper, you mentioned the introduction of a simplified class protocol to generate a 68 subjects dataset from three datasets (smic: 16 subjects, samm:32 subjects, and casme2:26 subjects, total is 74 subjects). Can you tell me how to do this?

**Comment by davidnvq** [comment]
The `simplified class protocol` was indeed introduced by the **Challenge organizers**. 
* In SMIC, there are 3 class labels: Positive, Negative and Surprise.
* In CASME II, there are 5 class labels: Happiness, Disgust, Repression, Surprise, Others.
* In SAMM, there are 7 class labels.

So to combine all 3 datasets together, we need to have the same class labels, right? The organizers just relabeled CASME II, and SAMM datasets into only 3 class labels (Positive, Negative and Surprise). For example, a label Happiness will be a label `Positive`, etc.

**Comment by Ritian-Li** [comment]
@davidnvq  Many thanks for your answer！: )

**Comment by davidnvq** [comment]
You're welcome. Let me close the issue.
