### ISSUE TITLE
dataset, How to get?

### ISSUE THREAD

**Issue by wahyuspb** [davidnvq/me_recognition#7]
Hi @davidnvq  ,thank you for your work.could you give a link for SAMM and SMIC datasets links? thank you for your reply

**Comment by davidnvq** [comment]
Hi @wahyuspb, the datasets in this repo indeed were parts of [the Facial micro-Expression  challenge in 2019](https://facial-micro-expressiongc.github.io/MEGC2019/). You may find more information about how to download the datasets.
