### ISSUE TITLE
About SMIC Dataset Application

### ISSUE THREAD

**Issue by likemby** [davidnvq/me_recognition#8]
Hello, I am Ma Bingyang, a postgraduate from Northestern University, China.
I tried to access this website——“http://http://www.cse.oulu.fi/SMICDatabas”to download the protocol  and apply for the SMIC dataset, but failed in the first step.(Some help has been requested)

Therefore, I'd like you to tell me how to do, like sending me the agreement documents and contact email.

I sincerely appreciate your guidance.

**Comment by davidnvq** [comment]
@likemby Thank you for your message. In fact, I'm not the owner of this dataset.
However, you can get the dataset by sending an email to Prof. Xiaobai (xiaobai.li@oulu.fi). 
After that, Prof. Xiaobai will ask you to sign an agreement and instruct you on how to download the dataset.

More information: https://www.oulu.fi/cmvs/node/41319
