### ISSUE TITLE
A question about the picture in your paper

### ISSUE THREAD

**Issue by likemby** [davidnvq/me_recognition#9]
![04da4c41796432cb239b45ea8b44651](https://user-images.githubusercontent.com/53123260/139082932-03abc65a-d408-4faa-9df3-38c5b4d919a2.png)
I have read your paper  and now have one question. In this picture, I think the red line indicates the predicted apex frame, but I don't know what the blue line is indicating. 
Hope to get your help!

**Comment by davidnvq** [comment]
Sorry for the confusion. Indeed the blue lines indicate the positions of 10 frames before and after the apex frame. Because the apex frame is not provided in some datasets, the predicted apex frame is just an estimate (with an acceptable error of +/- 10 frames).
